// examples/wrappers/react/App.tsx
/**
 *    ▄▄▄▄
 *  ▄█▀▀███▄▄              █▄
 *  ██    ██ ▄             ██
 *  ██    ██ ████▄▄█▀█▄ ▄████ ▄█▀█▄▀██ ██▀
 *  ██  ▄ ██ ██   ██▄█▀ ██ ██ ██▄█▀  ███
 *   ▀█████▄▄█▀  ▄▀█▄▄▄▄█▀███▄▀█▄▄▄▄██ ██▄
 *        ▀█
 *
 *  Copyright (C) 2026 — 2026, Qredex, LTD. All Rights Reserved.
 *
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  Licensed under the Apache License, Version 2.0. See LICENSE for the full license text.
 *  You may not use this file except in compliance with that License.
 *  Unless required by applicable law or agreed to in writing, software distributed under the
 *  License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 *  either express or implied. See the License for the specific language governing permissions
 *  and limitations under the License.
 *
 *  If you need additional information or have any questions, please email: copyright@qredex.com
 */

import { useEffect, useRef, useState } from 'react';
import { useQredexAgent } from '@qredex/react';
import {
  EXAMPLE_AGENT_CONFIG,
  EXAMPLE_LINKS,
  PRODUCTS,
  WRAPPER_PAGE_CONFIG,
  copyText,
  createEmptySnapshot,
  createExampleHarness,
  formatCurrency,
  getExampleLinkClass,
  snippetToken,
  type ExampleHarness,
  type ExampleSnapshot,
} from '../../shared/wrapper-example';

const activeKind = 'react' as const;
const config = WRAPPER_PAGE_CONFIG.react;

export function App() {
  const { agent, state } = useQredexAgent(EXAMPLE_AGENT_CONFIG);
  const harnessRef = useRef<ExampleHarness | null>(null);
  const [snapshot, setSnapshot] = useState<ExampleSnapshot>(createEmptySnapshot());

  useEffect(() => {
    const harness = createExampleHarness(agent, config);
    harnessRef.current = harness;

    const unsubscribe = harness.subscribe((nextSnapshot) => {
      setSnapshot(nextSnapshot);
    });

    harness.start();

    return () => {
      unsubscribe();
      harness.destroy();
      harnessRef.current = null;
    };
  }, [agent]);

  return (
    <main className="shell">
      <nav className="example-nav">
        <a className="example-home-link" href="/examples/index.html">
          Examples
        </a>
        <div className="example-link-row">
          {EXAMPLE_LINKS.map((link) => (
            <a
              key={link.kind}
              className={getExampleLinkClass(link.kind, activeKind)}
              href={link.href}
            >
              {link.label}
            </a>
          ))}
        </div>
      </nav>

      <section className="hero">
        <div>
          <p className="eyebrow">{config.eyebrow}</p>
          <h1>{config.title}</h1>
          <p className="hero-copy">{config.heroCopy}</p>
          <div className="hero-notes">
            {config.heroNotes.map((note) => (
              <span key={note}>{note}</span>
            ))}
          </div>
        </div>
        <div className="hero-actions">
          <button
            className="btn btn-primary"
            id="set-intent-button"
            type="button"
            onClick={() => {
              harnessRef.current?.setRandomIntent();
            }}
          >
            Set Random IIT
          </button>
          <button
            className="btn btn-secondary"
            id="reload-button"
            type="button"
            onClick={() => {
              harnessRef.current?.reloadPage();
            }}
          >
            Refresh Page
          </button>
        </div>
      </section>

      <section className="layout">
        <div className="stack">
          <section className="panel">
            <div className="panel-header">
              <div>
                <p className="panel-label">Product Shelf</p>
                <h2>Add test products</h2>
              </div>
            </div>
            <div className="catalog">
              {PRODUCTS.map((product) => (
                <article className="product-card" key={product.id}>
                  <div>
                    <p className="product-price">{formatCurrency(product.price)}</p>
                    <h3>{product.name}</h3>
                    <p className="product-copy">{product.description}</p>
                  </div>
                  <button
                    className="btn btn-primary"
                    data-add-product={product.id}
                    type="button"
                    onClick={() => {
                      harnessRef.current?.addProduct(product.id);
                    }}
                  >
                    Add to cart
                  </button>
                </article>
              ))}
            </div>
          </section>

          <section className="panel">
            <div className="panel-header">
              <div>
                <p className="panel-label">Agent Runtime</p>
                <h2>Current session</h2>
              </div>
              <span className="badge">Real React app</span>
            </div>

            <div className="status-grid">
              <article className="metric">
                <span className="metric-label">IIT</span>
                <strong className="metric-value" id="status-iit">
                  {snippetToken(state.iit)}
                </strong>
              </article>
              <article className="metric">
                <span className="metric-label">PIT</span>
                <strong className="metric-value" id="status-pit">
                  {snippetToken(state.pit)}
                </strong>
              </article>
              <article className="metric">
                <span className="metric-label">Cart items</span>
                <strong className="metric-value" id="status-count">
                  {snapshot.unitCount}
                </strong>
              </article>
              <article className="metric">
                <span className="metric-label">Cart state</span>
                <strong className="metric-value" id="status-cart-state">
                  {state.cartState}
                </strong>
              </article>
            </div>

            <details className="runtime-details">
              <summary className="runtime-summary">
                <span>Session details</span>
                <span>URL + wrapper note</span>
              </summary>
              <div className="state-box">
                <p className="state-title">Visible URL</p>
                <code id="current-url">{snapshot.currentUrl}</code>
              </div>

              <div className="state-box">
                <p className="state-title">Live harness note</p>
                <p id="persistence-note">{config.runtimeNote}</p>
              </div>
            </details>
          </section>

          <section className="panel">
            <div className="panel-header">
              <div>
                <p className="panel-label">Event feed</p>
                <h2>Agent and cart activity</h2>
              </div>
            </div>
            <div className="log" id="log">
              {snapshot.logs.map((entry) => (
                <div className={`log-entry log-${entry.level}`} key={entry.id}>
                  [{entry.time}] {entry.message}
                </div>
              ))}
            </div>
          </section>
        </div>

        <aside className="side-stack">
          <section className="panel cart-panel">
            <div className="panel-header">
              <div>
                <p className="panel-label">Cart</p>
                <h2>Persistent cart</h2>
              </div>
              <button
                className="btn btn-danger"
                id="empty-cart-button"
                type="button"
                onClick={() => {
                  harnessRef.current?.emptyCart();
                }}
              >
                Empty cart
              </button>
            </div>

            <div className="cart-summary">
              <div>
                <span className="summary-label">Lines</span>
                <strong id="summary-lines">{snapshot.lineCount}</strong>
              </div>
              <div>
                <span className="summary-label">Units</span>
                <strong id="summary-units">{snapshot.unitCount}</strong>
              </div>
              <div>
                <span className="summary-label">Subtotal</span>
                <strong id="summary-subtotal">{formatCurrency(snapshot.subtotal)}</strong>
              </div>
            </div>

            <div className="cart-list" id="cart-list">
              {snapshot.lines.length === 0 ? (
                <div className="empty-state">
                  <p>Your cart is empty.</p>
                  <span>Add a product to trigger the agent against a non-empty cart.</span>
                </div>
              ) : (
                snapshot.lines.map((line) => (
                  <article className="cart-line" key={line.product.id}>
                    <div>
                      <p className="cart-line-title">{line.product.name}</p>
                      <p className="cart-line-meta">{formatCurrency(line.product.price)} each</p>
                    </div>
                    <div className="quantity-controls">
                      <button
                        className="qty-btn"
                        data-decrement-product={line.product.id}
                        type="button"
                        onClick={() => {
                          harnessRef.current?.decrementProduct(line.product.id);
                        }}
                      >
                        −
                      </button>
                      <span>{line.quantity}</span>
                      <button
                        className="qty-btn"
                        data-increment-product={line.product.id}
                        type="button"
                        onClick={() => {
                          harnessRef.current?.addProduct(line.product.id);
                        }}
                      >
                        +
                      </button>
                    </div>
                  </article>
                ))
              )}
            </div>
          </section>

          <section className="panel panel-soft bridge-panel">
            <div className="panel-header">
              <div>
                <p className="panel-label">{config.bridgeLabel}</p>
                <h2>{config.bridgeTitle}</h2>
              </div>
              <span className="badge">{config.badge}</span>
            </div>
            <p className="bridge-copy">{config.bridgeCopy}</p>
            <div className="state-box bridge-meta">
              <p className="state-title">Install</p>
              <div className="install-command-row">
                <code className="install-command">{config.installCommand}</code>
                <button
                  aria-label="Copy install command"
                  className="copy-install-button"
                  title="Copy install command"
                  type="button"
                  onClick={() => {
                    void copyText(config.installCommand);
                  }}
                >
                  ⧉
                </button>
              </div>
            </div>
            <details className="bridge-details">
              <summary className="bridge-summary">
                <span>Bridge code example</span>
                <span>{config.codeLanguage.toUpperCase()}</span>
              </summary>
              <div className="code-card">
                <div className="code-card-header">
                  <span>{config.codeLanguage.toUpperCase()}</span>
                </div>
                <pre className="code-block">
                  <code>{config.codeSample}</code>
                </pre>
              </div>
            </details>
          </section>
        </aside>
      </section>
    </main>
  );
}

// examples/wrappers/svelte/App.svelte
<!--
    ▄▄▄▄
  ▄█▀▀███▄▄              █▄
  ██    ██ ▄             ██
  ██    ██ ████▄▄█▀█▄ ▄████ ▄█▀█▄▀██ ██▀
  ██  ▄ ██ ██   ██▄█▀ ██ ██ ██▄█▀  ███
   ▀█████▄▄█▀  ▄▀█▄▄▄▄█▀███▄▀█▄▄▄▄██ ██▄
        ▀█

  Copyright (C) 2026 — 2026, Qredex, LTD. All Rights Reserved.

  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.

  Licensed under the Apache License, Version 2.0. See LICENSE for the full license text.
  You may not use this file except in compliance with that License.
  Unless required by applicable law or agreed to in writing, software distributed under the
  License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
  either express or implied. See the License for the specific language governing permissions
  and limitations under the License.

  If you need additional information or have any questions, please email: copyright@qredex.com
-->
<script lang="ts">
  import { onMount } from 'svelte';
  import { useQredexAgent } from '@qredex/svelte';
  import {
    EXAMPLE_AGENT_CONFIG,
    EXAMPLE_LINKS,
    PRODUCTS,
    WRAPPER_PAGE_CONFIG,
    copyText,
    createEmptySnapshot,
    createExampleHarness,
    formatCurrency,
    getExampleLinkClass,
    snippetToken,
    type ExampleHarness,
  } from '../../shared/wrapper-example';

  const activeKind = 'svelte' as const;
  const config = WRAPPER_PAGE_CONFIG.svelte;
  const { agent, state: agentStateStore } = useQredexAgent(EXAMPLE_AGENT_CONFIG);
  let snapshot = createEmptySnapshot();
  let harness: ExampleHarness | null = null;

  onMount(() => {
    harness = createExampleHarness(agent, config);
    const unsubscribe = harness.subscribe((nextSnapshot) => {
      snapshot = nextSnapshot;
    });

    harness.start();

    return () => {
      unsubscribe();
      harness?.destroy();
      harness = null;
    };
  });

  function addProduct(productId: string) {
    harness?.addProduct(productId);
  }

  function decrementProduct(productId: string) {
    harness?.decrementProduct(productId);
  }

  function emptyCart() {
    harness?.emptyCart();
  }

  function setRandomIntent() {
    harness?.setRandomIntent();
  }

  function reloadPage() {
    harness?.reloadPage();
  }
</script>

<main class="shell">
  <nav class="example-nav">
    <a class="example-home-link" href="/examples/index.html">Examples</a>
    <div class="example-link-row">
      {#each EXAMPLE_LINKS as link (link.kind)}
        <a class={getExampleLinkClass(link.kind, activeKind)} href={link.href}>{link.label}</a>
      {/each}
    </div>
  </nav>

  <section class="hero">
    <div>
      <p class="eyebrow">{config.eyebrow}</p>
      <h1>{config.title}</h1>
      <p class="hero-copy">{config.heroCopy}</p>
      <div class="hero-notes">
        {#each config.heroNotes as note (note)}
          <span>{note}</span>
        {/each}
      </div>
    </div>
    <div class="hero-actions">
      <button class="btn btn-primary" id="set-intent-button" type="button" on:click={setRandomIntent}>
        Set Random IIT
      </button>
      <button class="btn btn-secondary" id="reload-button" type="button" on:click={reloadPage}>
        Refresh Page
      </button>
    </div>
  </section>

  <section class="layout">
    <div class="stack">
      <section class="panel">
        <div class="panel-header">
          <div>
            <p class="panel-label">Product Shelf</p>
            <h2>Add test products</h2>
          </div>
        </div>
        <div class="catalog">
          {#each PRODUCTS as product (product.id)}
            <article class="product-card">
              <div>
                <p class="product-price">{formatCurrency(product.price)}</p>
                <h3>{product.name}</h3>
                <p class="product-copy">{product.description}</p>
              </div>
              <button
                class="btn btn-primary"
                data-add-product={product.id}
                type="button"
                on:click={() => addProduct(product.id)}
              >
                Add to cart
              </button>
            </article>
          {/each}
        </div>
      </section>

      <section class="panel">
        <div class="panel-header">
          <div>
            <p class="panel-label">Agent Runtime</p>
            <h2>Current session</h2>
          </div>
          <span class="badge">Real Svelte app</span>
        </div>

        <div class="status-grid">
          <article class="metric">
            <span class="metric-label">IIT</span>
            <strong class="metric-value" id="status-iit">{snippetToken($agentStateStore.iit)}</strong>
          </article>
          <article class="metric">
            <span class="metric-label">PIT</span>
            <strong class="metric-value" id="status-pit">{snippetToken($agentStateStore.pit)}</strong>
          </article>
          <article class="metric">
            <span class="metric-label">Cart items</span>
            <strong class="metric-value" id="status-count">{snapshot.unitCount}</strong>
          </article>
          <article class="metric">
            <span class="metric-label">Cart state</span>
            <strong class="metric-value" id="status-cart-state">{$agentStateStore.cartState}</strong>
          </article>
        </div>

        <details class="runtime-details">
          <summary class="runtime-summary">
            <span>Session details</span>
            <span>URL + wrapper note</span>
          </summary>
          <div class="state-box">
            <p class="state-title">Visible URL</p>
            <code id="current-url">{snapshot.currentUrl}</code>
          </div>

          <div class="state-box">
            <p class="state-title">Live harness note</p>
            <p id="persistence-note">{config.runtimeNote}</p>
          </div>
        </details>
      </section>

      <section class="panel">
        <div class="panel-header">
          <div>
            <p class="panel-label">Event feed</p>
            <h2>Agent and cart activity</h2>
          </div>
        </div>
        <div class="log" id="log">
          {#each snapshot.logs as entry (entry.id)}
            <div class={`log-entry log-${entry.level}`}>[{entry.time}] {entry.message}</div>
          {/each}
        </div>
      </section>
    </div>

    <aside class="side-stack">
      <section class="panel cart-panel">
        <div class="panel-header">
          <div>
            <p class="panel-label">Cart</p>
            <h2>Persistent cart</h2>
          </div>
          <button class="btn btn-danger" id="empty-cart-button" type="button" on:click={emptyCart}>
            Empty cart
          </button>
        </div>

        <div class="cart-summary">
          <div>
            <span class="summary-label">Lines</span>
            <strong id="summary-lines">{snapshot.lineCount}</strong>
          </div>
          <div>
            <span class="summary-label">Units</span>
            <strong id="summary-units">{snapshot.unitCount}</strong>
          </div>
          <div>
            <span class="summary-label">Subtotal</span>
            <strong id="summary-subtotal">{formatCurrency(snapshot.subtotal)}</strong>
          </div>
        </div>

        <div class="cart-list" id="cart-list">
          {#if snapshot.lines.length === 0}
            <div class="empty-state">
              <p>Your cart is empty.</p>
              <span>Add a product to trigger the agent against a non-empty cart.</span>
            </div>
          {:else}
            {#each snapshot.lines as line (line.product.id)}
              <article class="cart-line">
                <div>
                  <p class="cart-line-title">{line.product.name}</p>
                  <p class="cart-line-meta">{formatCurrency(line.product.price)} each</p>
                </div>
                <div class="quantity-controls">
                  <button
                    class="qty-btn"
                    data-decrement-product={line.product.id}
                    type="button"
                    on:click={() => decrementProduct(line.product.id)}
                  >
                    −
                  </button>
                  <span>{line.quantity}</span>
                  <button
                    class="qty-btn"
                    data-increment-product={line.product.id}
                    type="button"
                    on:click={() => addProduct(line.product.id)}
                  >
                    +
                  </button>
                </div>
              </article>
            {/each}
          {/if}
        </div>
      </section>

      <section class="panel panel-soft bridge-panel">
        <div class="panel-header">
          <div>
            <p class="panel-label">{config.bridgeLabel}</p>
            <h2>{config.bridgeTitle}</h2>
          </div>
          <span class="badge">{config.badge}</span>
        </div>
        <p class="bridge-copy">{config.bridgeCopy}</p>
        <div class="state-box bridge-meta">
          <p class="state-title">Install</p>
          <div class="install-command-row">
            <code class="install-command">{config.installCommand}</code>
            <button
              aria-label="Copy install command"
              class="copy-install-button"
              title="Copy install command"
              type="button"
              on:click={() => void copyText(config.installCommand)}
            >
              ⧉
            </button>
          </div>
        </div>
        <details class="bridge-details">
          <summary class="bridge-summary">
            <span>Bridge code example</span>
            <span>{config.codeLanguage.toUpperCase()}</span>
          </summary>
          <div class="code-card">
            <div class="code-card-header">
              <span>{config.codeLanguage.toUpperCase()}</span>
            </div>
            <pre class="code-block"><code>{config.codeSample}</code></pre>
          </div>
        </details>
      </section>
    </aside>
  </section>
</main>
